version: '3.8'
services:

  client-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"

  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db-dev
      - mongo-db-dev
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules

  mongo-db-dev:
    image: mongo:4.4
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=mongo
    #   - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"

  postgres-db-dev:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=squadhelp-dev
    ports:
      - "5432:5432"

